### PR TITLE
Polish Language

### PR DESCRIPTION
**Pull request by oskarniziol**
- Polish Language

### CODE REVIEW

**Comment by GIGABAIT93** [comment]
Hi Make Pull Request

**Comment by PadowYT2** [comment]
Notes: wrong quotes when u did "Polish"

and please, no https://cdn.padow.ru/u3Io

**Comment by Mubeen142** [comment]
Add Polish Translation

**Comment by Mubeen142** [comment]
Thanks,

Please fix the conflicts before we merge the pr.

**Pull request closed without merging**
