### PR TITLE
Update

### PR DESCRIPTION
**Pull request by Justman10000**

### CODE REVIEW

**Comment by PadowYT2** [comment]
Sorry, we are going to redo our languages

**Comment by Justman10000** [comment]
Are you fucking with me right now? You're not able to fucking answer within at least 2 weeks, only to destroy my work because it suddenly occurs to you that the multilingual system is being updated? Recognise the mistakes...

**Comment by Justman10000** [comment]
And why do you have access here at all to be able to close and merge PRs?

**Comment by PadowYT2** [comment]
> You're not able to fucking answer within at least 2 weeks

Even if we merged the PR, everything would be still gone

> only to destroy my work because it suddenly occurs to you that the multilingual system is being updated?

It is not only all work, it is all PR's that includes languages

> And why do you have access here at all to be able to close and merge PRs?

Because I'm an admin of Vertisan

**Pull request closed without merging**
